name: Build and Deploy
on:
  push:
    branches:
      - vanilla-svelte
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Svelte Build
        run: |
          npm ci
          npm run build
        
      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist